// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_hB0s3BQ0xXRBnNa2HCBjwZvO1_4foJI',
    appId: '1:43432258096:web:3dbcb0bdd2a22b1d0b9bf5',
    messagingSenderId: '43432258096',
    projectId: 'infit-86db2',
    authDomain: 'infit-86db2.firebaseapp.com',
    databaseURL: 'https://infit-86db2-default-rtdb.firebaseio.com',
    storageBucket: 'infit-86db2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnt0V-9EYLuyBgO6rctDIQzpOMq8JrteQ',
    appId: '1:43432258096:android:3aaf8b3525f10a6e0b9bf5',
    messagingSenderId: '43432258096',
    projectId: 'infit-86db2',
    databaseURL: 'https://infit-86db2-default-rtdb.firebaseio.com',
    storageBucket: 'infit-86db2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQF4ABLFTcx9atRQXf97vYKyf6lYcdBGI',
    appId: '1:43432258096:ios:2a803136e40d94410b9bf5',
    messagingSenderId: '43432258096',
    projectId: 'infit-86db2',
    databaseURL: 'https://infit-86db2-default-rtdb.firebaseio.com',
    storageBucket: 'infit-86db2.appspot.com',
    iosBundleId: 'com.example.ehrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQF4ABLFTcx9atRQXf97vYKyf6lYcdBGI',
    appId: '1:43432258096:ios:2a803136e40d94410b9bf5',
    messagingSenderId: '43432258096',
    projectId: 'infit-86db2',
    databaseURL: 'https://infit-86db2-default-rtdb.firebaseio.com',
    storageBucket: 'infit-86db2.appspot.com',
    iosBundleId: 'com.example.ehrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_hB0s3BQ0xXRBnNa2HCBjwZvO1_4foJI',
    appId: '1:43432258096:web:d02355d21d443dd50b9bf5',
    messagingSenderId: '43432258096',
    projectId: 'infit-86db2',
    authDomain: 'infit-86db2.firebaseapp.com',
    databaseURL: 'https://infit-86db2-default-rtdb.firebaseio.com',
    storageBucket: 'infit-86db2.appspot.com',
  );
}
